name: pack

on:
  push:
    tags:
    - '*'

jobs:
    build:
      name: Create a react native project
      runs-on: ubuntu-latest
      steps:
      - name: Set env
        run: echo ::set-env name=VERSION::${GITHUB_REF#refs/*/}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Init Project 
        run: npx react-native init rncn --version ${{ env.VERSION }}
      - name: Install pods
        run: sudo gem install cocoapods --no-document && cd rncn/ios && pod install
      - name: Zip
        uses: nguyenquyhy/zip-release@v0.3.0
        with:
          filename: release/release.zip
          workingDirectory: rncn
      - name: Push to repo
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: ${{ env.VERSION }}
          directory: rncn/release
          
      
        
