name: pack

on:
  push:
    tags:
    - '*'

jobs:
    build:
      name: Create a react native project
      runs-on: macos-latest
      steps:
      - name: Set env
        run: echo ::set-env name=VERSION::${GITHUB_REF#refs/*/} && sudo gem install cocoapods --no-document
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Init Project 
        run: npx react-native init rncn --version ${{ env.VERSION }}
      - name: Zip
        run: rm -rf rncn/node_modules && zip -r -X rncn.zip rncn && rm -rf rncn
      - name: Push to repo
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: ${{ env.VERSION }}
          
      
        
